"use client";

import React, { useState } from "react";
import { Button } from "../ui/button";

export const [MyData, setMyData] = useState([
  {
    id: "1",
    description: "Call Parents",
    status: "To Do",
    date: "2024-10-01",
    // delete: <Button>Delete</Button>,
    // update: <Button>Update</Button>,
    delete: null,
    update: null,
  },
  {
    id: "2",
    description: "Call Parents",
    status: "To Do",
    date: "2024-10-01",
    // delete: <Button>Delete</Button>,
    // update: <Button>Update</Button>,
    delete: null,
    update: null,
  },
  {
    id: "3",
    description: "Call Parents",
    status: "To Do",
    date: "2024-10-01",
    // delete: <Button>Delete</Button>,
    // update: <Button>Update</Button>,
    delete: null,
    update: null,
  },
  {
    id: "4",
    description: "Call Parents",
    status: "To Do",
    date: "2024-10-01",
    delete: null,
    update: null,
    // delete: <Button>Delete</Button>,
    // update: <Button>Update</Button>,
  },
  {
    id: "5",
    description: "Call Parents",
    status: "To Do",
    date: "2024-10-01",
    delete: null,
    update: null,
  },
  {
    id: "6",
    description: "Call Parents",
    status: "To Do",
    date: "2024-10-01",
    // delete: <Button>Delete</Button>,
    // update: <Button>Update</Button>,
    delete: null,
    update: null,
  },
  {
    id: "7",
    description: "Call Parents",
    status: "To Do",
    date: "2024-10-01",
    // delete: <Button>Delete</Button>,
    // update: <Button>Update</Button>,
    delete: null,
    update: null,
  },
  {
    id: "8",
    description: "Call Parents",
    status: "To Do",
    date: "2024-10-01",
    // delete: <Button>Delete</Button>,
    // update: <Button>Update</Button>,
    delete: null,
    update: null,
  },
]);
